### ISSUE TITLE
Single LED vs Sequential LED Position

### ISSUE THREAD

**Issue by 10AE0739** [Keith-N/KaN-Gauge#5]
Version 1.1.7. Testing Sequential LEDs with Alerts vs Single LED with Alert for oil pressure PSI. Sequential works perfectly. 10-19 psi is 1 LED, 20-29 is 2 LEDS, 30-39 is 3 LEDS, etc. I would expect that the last LED of full sequential would be the location of the single LED, but the single LED is one LED further. I have a video if that'll help.

**Comment by 10AE0739** [comment]
For single LED, p = p/10; should be p = (p/10) - 1. This would better match the functionality of the sequential LEDs. In my opinion, using oil pressure as an example, sequential LEDs works perfectly but single LED looks one LED too high. Considering p is set the same for both functions, but the for loop is i < p which is more similar to p = (p / 10) - 1.

```
// Illuminate LEDs sequentially 0-10
void sequentialLed(int p)
{

  p = p / 10;
  ledOff();

  for (int i = 0; i < p; i++)
  {
    digitalWrite(indicatorLed[i], HIGH);
  }
}

// Illuminate single LED 0-10
void singleLed(int p)
{

  p = p / 10;
  ledOff();

  digitalWrite(indicatorLed[p], HIGH);
}

// Illuminate all LED 0-12
void sequentialLedAll(int p)
{
```

**Comment by Keith-N** [comment]
Thank you for opening this. For some reason I have not been receiving notifications (even though they have not been disabled) and I am just seeing this now. I will try to start looking into these this week.

It does appear that sequential will always be 1 less due to the way that the for loop is constructed. It sounds like this was tested using the default 0 to 100 PSI range?

**Comment by 10AE0739** [comment]
Yes, I haven’t tried changing any ranges. I do believe the sequential makes more sense, so the fix would be to make the single match the sequential?

**Comment by Keith-N** [comment]
Currently the way that this works is that a percentage is calculated using the current sensor value and then that percentage is used to control the number of LEDs. That is then used to decide the illuminated LEDs based on the percentage and the total number of LEDs in that set. The min value will correspond to the first value the first LED is illuminated and the max will be the upper most used to establish the range.

I believe am seeing potentially two issues here. One is that the LEDs are inconsistent due to the for loop not going up to to current p value, and the second is that the functionality is not as clear as it could be in regards to the limits.

I think that the best solution may be to make the minimum value the target for the first LED and use the maximum value as the target for the last LED. So that if the value exceeds the minimum then the first LED would be on, and if the maximum is exceeded the last LED would be on.

**Comment by 10AE0739** [comment]
As far as min and max, that makes sense. What about the in between values.  I think the for loop is working more intuitively and that the single LED isn't.  Oil PSI from 0 to 100 PSI with 10 LEDS is a good example. I see 4 LEDS (when sequential is active) and I know the Oil Pressure is between 40 and 49. Currently, the single LED would light up LED 5 for 40-49 and that's less intuitive. Given the 0 to n-1 indexing, the for loop looks correct and the single LED should be (p / 10) - 1. By the way, I'd be glad to help with testing and coding if you could show me how to compile the code. I'd also be glad to talk through the coding logic with you for debugging if you're interested. I can have Jesse send you my contact info if you'd like.

**Comment by Keith-N** [comment]
After looking at it more, the single LED should be at p-1 like you said. It actually could cause it to overshoot the defined range too. This will be added to the next build.

commit 57ae7d356b240db027086be2024f2b247801b8a0

**Comment by Keith-N** [comment]
I just added release 1.1.8. This should address most of the current issues. Please let me know how it works for you.
